### PR TITLE
chore: upgrade to milestone 8

### LINKED ISSUE #155: Upgrade extensions to support EDC `v0.0.1-milestone-8`
# Bug Report / Feature request

## Description

_A clear and concise description of the bug._
_If applicable, add screenshots or other information to help explain your problem._

I would like to use these extensions with EDC `v0.0.1-milestone-8`, because of other extensions depending on this version. Therefore I am a bit in a dependency conflict, because these extensions are working fine with `v0.0.1-milestone-7` and the others are working fine with `v0.0.1-milestone-8`. I think in this case the upgrade is preferred over the downgrade..

### Expected Behavior

_A clear and concise description of what you expected to happen._

Just work with `v0.0.1-milestone-8`. No exceptions in the log.

### Observed Behavior

_A clear and concise description of what happened instead._

Compiles without error. But I am getting this Exception in the log:

```
2023-02-28 12:01:27 Initialized IDS Core
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.<init>(org.eclipse.edc.spi.monitor.Monitor, okhttp3.OkHttpClient, org.eclipse.edc.protocol.ids.spi.service.DynamicAttributeTokenService, com.fasterxml.jackson.databind.ObjectMapper)'
        at de.sovity.extension.broker.BrokerExtension.registerBrokerMessageSenders(BrokerExtension.java:255)
        at de.sovity.extension.broker.BrokerExtension.initialize(BrokerExtension.java:131)
        at org.eclipse.edc.boot.system.injection.lifecycle.InitializePhase.initialize(InitializePhase.java:37)
        at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.initialize(ExtensionLifecycleManager.java:61)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:152)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:222)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:87)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:75)
```

## Steps to Reproduce

Basically just upgrade in a sample project the edc-version from `v0.0.1-milestone-7` to `v0.0.1-milestone-8` and see what happens in the log on startup.

## Context Information

_Add any other context about the problem here._

- Environment: MDS Dev-Environment
- Used version:
  - EDC: `v0.0.1-milestone-8`
  - sovity/edc-extensions: v1.3.0
- Time: 2023-02-28 12:01:27 UTC
- Logs: see above
- Parameter: _happens on startup_
- OS: Debian Docker Image
- ...

## Possible Implementation and Work Breakdown

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

I don't know.

### PR DESCRIPTION
**Pull request by tmberthold**
Upgrades the current edc-extensions repo to milestone 8 and adds the extended HTTP Pull postman collection.
Closes #155

### CODE REVIEW

File: connector/Dockerfile [hunk 1]
```diff
@@ -26,7 +26,7 @@ COPY --from=build /home/gradle/project/connector/build/libs/app.jar /app
 COPY ./connector/src/main/resources/logging.properties /app
 
 # health status is determined by the availability of the /health endpoint
-HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl -H "X-Api-Key: $EDC_API_AUTH_KEY" --fail http://localhost:8181/api/check/health
+# HEALTHCHECK --interval=5s --timeout=5s --retries=10 CMD curl -H "X-Api-Key: $EDC_API_AUTH_KEY" --fail http://localhost:8181/api/check/health
```
Comment (efiege) [inline connector/Dockerfile:29]: Please fix the Health-Check

File: extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java [hunk 2]
```diff
@@ -79,7 +79,7 @@ public class ClearingHouseExtension implements ServiceExtension {
     private Hostname hostname;
 
     @Inject
-    private OkHttpClient okHttpClient;
+    private EdcHttpClient edcHttpClient;
```
Comment (efiege) [inline extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java:82]: Can be removed as it is not used anymore

File: extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java [hunk 3]
```diff
@@ -155,7 +155,7 @@ private void registerCommonTypes(TypeManager typeManager) {
     }
 
     private void registerClearingHouseMessageSenders(ServiceExtensionContext context) {
-        var httpClient = context.getService(OkHttpClient.class);
+        var httpClient = context.getService(EdcHttpClient.class);
```
Comment (efiege) [inline extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java:158]: Can be removed as it is not used anymore

**Review by efiege — CHANGES_REQUESTED** [review]

File: extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java (hunk 3 above)
Comment (tmberthold) [reply extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java:158]: Needed for `IdsMultipartSender`?!

File: connector/Dockerfile (hunk 1 above)
Comment (tmberthold) [reply connector/Dockerfile]: I have moved the health check under the management context, however the warnings about an outdated health URL continue to come up there. I assume this is a buggy implementation, because after all we are now using the API endpoint of the management context as the message says. Would wait for MS9 here.

Management-Context:
`http://localhost:11004/api/v1/management/check/health`
instead of the old
`http://localhost:8181/api/check/health`

Comment (tmberthold) [reply connector/Dockerfile]: Just as note: here's the original EDC-Connector PR, which changed the endpoints:
https://github.com/eclipse-edc/Connector/pull/2217/files
